export const COLOR_MAP: Record<string, string> = {
  "01": "Rojo",
  "1": "Rojo",
  "02": "Vino tinto",
  "2": "Vino tinto",
  "03": "Verde militar",
  "3": "Verde militar",
  "04": "Negro",
  "4": "Negro",
  "05": "Rosa",
  "5": "Rosa",
  "06": "Azul claro",
  "6": "Azul claro",
  "061": "CAMUFLADO",
  "07": "Azul medio",
  "7": "Azul medio",
  "08": "Azul oscuro",
  "8": "Azul oscuro",
  "09": "Hielo",
  "9": "Hielo",
  "10": "Amarillo",
  "11": "Café",
  "12": "Gris claro",
  "13": "Gris oscuro",
  "14": "Blanco",
  "15": "Beige",
  "16": "kaki",
  "17": "Mandarina",
  "18": "Arena",
  "19": "Marfil",
  "20": "Verde",
  "21": "Morado",
  "22": "Mostaza",
  "23": "Crema",
  "24": "Dorado",
  "25": "Plateado",
  "26": "Cereza",
  "27": "Fucsia",
  "28": "Azul rey",
  "29": "Berenjena",
  "30": "Terracota",
  "31": "Salmon",
  "32": "Verde claro",
  "33": "Naranja",
  "34": "MELON",
  "35": "SEMILLA",
  "36": "GRIS MEDIO",
  "37": "CARAMELO",
  "38": "AVELLANA",
  "39": "OCRE",
  "40": "CARMEL",
  "41": "GUAYABA",
  "42": "AGUA MARINA",
  "43": "VERDE JADE",
  "44": "CORAL",
  "45": "VERDE MENTA",
  "46": "LADRILLO",
  "47": "MAGENTA",
  "48": "Macadamia",
  "49": "Champaña",
  "50": "Canela",
  "51": "Verde oliva",
  "52": "BAMBU",
  "54": "Azul turqueza",
  "55": "TABACO",
  "56": "CAMEL",
  "569": "MORA",
  "57": "ORQUIDEA",
  "573": "PINK",
  "575": "ROSA PASTEL",
  "576": "ALMENDRA",
  "577": "FUCSIA NEON",
  "578": "NARANJA NEON",
  "579": "VERDE NEON",
  "58": "MALVA",
  "580": "NATURAL",
  "582": "VERDE MANZANA",
  "583": "CONFITE",
  "584": "ESMERALDA",
  "585": "LIMA",
  "586": "AZUL",
  "587": "HORTENSIA",
  "588": "PISTACHO",
  "589": "CELESTE",
  "59": "LILA",
  "590": "TURQUESA",
  "597": "MARRON",
  "598": "VERDE ESMERALDA",
  "599": "IVORY",
  "60": "DURAZNO",
  "600": "RUBOR",
  "601": "AVENA",
  "602": "TAUPE",
  "603": "VERDE LIMON",
  "607": "MOCCA",
  "608": "COCOA",
  "609": "NUDE",
  "611": "Curcuma",
  "612": "VERDE BOTELLA",
  "613": "GRIS",
  "614": "AZUL COBALTO",
  "615": "VAINILLA",
  "62": "PALO DE ROSA",
  "621": "LAVANDA",
  "625": "CHOCOLATE",
  "627": "NAVY",
  "63": "AZUL PETROLEO",
  "64": "MORA",
  "640": "MATCHA",
  "641": "PITON CANELA",
  "642": "CEBRA",
  "643": "PITON ALMENDRA",
  "644": "AZUL NUBE",
  "645": "ESTAMPADO",
  "646": "CACAO",
  "647": "PARDO",
  "648": "DIRTY",
  "649": "PLOMO",
  "650": "ROSADO",
  "651": "UVA",
  "T629": "ANIMAL PRINT",
  "t629": "ANIMAL PRINT",
  "T630": "ANIMAL PRINT CHOCOLATE",
  "t630": "ANIMAL PRINT CHOCOLATE",
  "T631": "ANIMAL PRINT KAKI",
  "t631": "ANIMAL PRINT KAKI",
  "T632": "ANIMAL PRINT NEGRO",
  "t632": "ANIMAL PRINT NEGRO",
  "T633": "ANIMAL PRINT ALMENDRA",
  "t633": "ANIMAL PRINT ALMENDRA",
  "T634": "ANIMAL PRINT BLANCO",
  "t634": "ANIMAL PRINT BLANCO",
  "T635": "ANIMAL PRINT CAMEL",
  "t635": "ANIMAL PRINT CAMEL",
  "T636": "ANIMAL PRINT IVORY",
  "t636": "ANIMAL PRINT IVORY",
  "T637": "ANIMAL PRINT BEIGE",
  "t637": "ANIMAL PRINT BEIGE",
  "T638": "ANIMAL PRINT AVENA",
  "t638": "ANIMAL PRINT AVENA",
  "T639": "ANIMAL PRINT GRIS",
  "t639": "ANIMAL PRINT GRIS",
  "T640": "ANIMAL PRINT MARRON",
  "t640": "ANIMAL PRINT MARRON",
  "T641": "CEBRA NEGRO",
  "t641": "CEBRA NEGRO",
  "T642": "CEBRA BEIGE",
  "t642": "CEBRA BEIGE",
  "T643": "CEBRA KAKI",
  "t643": "CEBRA KAKI",
  "T644": "CEBRA MARRON",
  "t644": "CEBRA MARRON",
  "T645": "CEBRA ALMENDRA",
  "t645": "CEBRA ALMENDRA"
};

export function translateColor(color: string | number | undefined | null): string {
  if (color === undefined || color === null) return "";
  const code = String(color).trim();
  if (!code) return "";

  // Try exact match
  if (COLOR_MAP[code]) {
    return COLOR_MAP[code];
  }

  // Try case-insensitive
  const lowerCode = code.toLowerCase();
  if (COLOR_MAP[lowerCode]) {
    return COLOR_MAP[lowerCode];
  }

  // Try parsing single-digit numeric code to pad with zero
  if (/^\d+$/.test(code)) {
    const padded = code.padStart(2, "0");
    if (COLOR_MAP[padded]) {
      return COLOR_MAP[padded];
    }
  }

  return code;
}
