/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProveedorRouteImport } from './routes/proveedor'
import { Route as IndexRouteImport } from './routes/index'

const ProveedorRoute = ProveedorRouteImport.update({
  id: '/proveedor',
  path: '/proveedor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proveedor': typeof ProveedorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proveedor': typeof ProveedorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proveedor': typeof ProveedorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/proveedor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proveedor'
  id: '__root__' | '/' | '/proveedor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProveedorRoute: typeof ProveedorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proveedor': {
      id: '/proveedor'
      path: '/proveedor'
      fullPath: '/proveedor'
      preLoaderRoute: typeof ProveedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProveedorRoute: ProveedorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
